spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    include: oauth
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
